# Generated by Django 5.2.1 on 2025-06-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='importance',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='teamsparticipants',
            name='place',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
