# Generated by Django 5.2.1 on 2025-06-10 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportapp', '0002_events_importance_teamsparticipants_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='importance',
        ),
    ]
