# Generated by Django 5.2.1 on 2025-06-10 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportapp', '0003_remove_events_importance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='categoryOfParticipants',
        ),
        migrations.CreateModel(
            name='ParticipantCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=256)),
                ('minValue', models.IntegerField(blank=True, null=True)),
                ('maxValue', models.IntegerField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='sportapp.events')),
            ],
        ),
    ]
