# Generated by Django 5.2.1 on 2025-06-10 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportapp', '0004_remove_events_categoryofparticipants_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantCategoryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportapp.participantcategorymodel')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportapp.events')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportapp.participants')),
            ],
        ),
    ]
