# Generated by Django 5.2.1 on 2025-06-10 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportapp', '0005_participantcategoryassignment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participantcategoryassignment',
            unique_together={('participant', 'event')},
        ),
    ]
