# Generated by Django 5.2.1 on 2025-06-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportapp', '0006_alter_participantcategoryassignment_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participants',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
