services:
  backend:
    build:
      context: ./sportapp
    container_name: django_backend
    command: ["sh", "/app/entrypoint.sh", "django"]
    env_file:
      - .env
    volumes:
      - ./sportapp:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    env_file:
      - .env
    ports:
      - "5050:80"
    depends_on:
      - db

  redis:
    image: redis:alpine
    ports: [ "6379:6379" ]
    volumes:
      - redis_data:/data

  celery_worker:
    build: ./sportapp
    command: ["sh", "/app/entrypoint.sh", "celery_worker"]
    env_file: .env
    volumes:
      - ./sportapp:/app
    depends_on:
    - backend
    - db
    - redis


  celery_beat:
    build: ./sportapp
    command: ["sh", "/app/entrypoint.sh", "celery_beat"]
    env_file: .env
    volumes:
      - ./sportapp:/app
    depends_on:
    - backend
    - db
    - redis

volumes:
  postgres_data:
  redis_data: